site_name: Les Stromates
site_description: Les stromates, par Clément d\'Alexandrie
site_author: Olivier Rey
copyright: Domaine public
google_analytics: ['UA-110156293-1', 'orey.github.io']
repo_url: https://github.com/orey/les-stromates/
#theme: readthedocs
site_dir: site
extra_css: [extra.css]
nav:
- Home:
    - 'Index': 'index.md'
    - 'Author': 'about.md'
- Livre1:
    - 'Chapitre 1': 'livre1/chapitre01.md'
    - 'Chapitre 2': 'livre1/chapitre02.md'
    - 'Chapitre 3': 'livre1/chapitre03.md'
    - 'Chapitre 4': 'livre1/chapitre04.md'
